#!/bin/bash
"""
🚀 NICEGOLD ENTERPRISE PROJECTP - LIVE SHARE QUICK START SCRIPT
สคริปต์สำหรับเริ่มการทำงานร่วมกันแบบ Live Share
"""

echo "🏢 NICEGOLD ENTERPRISE PROJECTP - LIVE SHARE SETUP"
echo "=================================================="
echo ""
echo "📋 คำแนะนำการเริ่ม Live Share:"
echo ""
echo "1️⃣ เริ่ม Live Share Session:"
echo "   - กด Ctrl+Shift+P (Windows/Linux) หรือ Cmd+Shift+P (Mac)"
echo "   - พิมพ์: Live Share: Start Collaboration Session"
echo "   - กด Enter"
echo ""
echo "2️⃣ หรือใช้ Status Bar:"
echo "   - ดูที่ status bar ด้านล่าง VS Code"
echo "   - คลิกที่ 'Live Share' หรือ ไอคอน Live Share"
echo "   - เลือก 'Start collaboration session'"
echo ""
echo "3️⃣ แชร์ลิงค์:"
echo "   - ลิงค์จะถูก copy ไปยัง clipboard อัตโนมัติ"
echo "   - แชร์ลิงค์กับทีมงาน"
echo "   - สามารถใช้งานผ่าน web browser หรือ VS Code"
echo ""
echo "🎯 ไฟล์สำคัญสำหรับ Collaboration:"
echo "   ✅ ProjectP.py (Main entry point)"
echo "   ✅ core/ (Core system modules)"
echo "   ✅ elliott_wave_modules/ (AI/ML modules)"
echo "   ✅ menu_modules/ (Menu system)"
echo "   ✅ config/ (Configuration files)"
echo ""
echo "🛡️ Security Tips:"
echo "   ⚠️ อย่าแชร์กับคนที่ไม่น่าเชื่อถือ"
echo "   ⚠️ ตรวจสอบ participants ที่เข้าร่วม"
echo "   ⚠️ ปิด session เมื่อเสร็จแล้ว"
echo ""
echo "📖 ดูคู่มือเต็ม: LIVE_SHARE_GUIDE.md"
echo ""
echo "🚀 พร้อมเริ่มการทำงานร่วมกัน!"
echo "=================================================="
